"""
Maps (Region, Source, Drop) -> point value, generated from the bingo sheet's
master "Points per item" reference (Cba_Conquers_Gielinor.xlsx), with Pet
entries (150 pts each, per the sheet's blanket pet rule) preserved from the
original tracker sheet plus prior corrections.

Regenerate this alongside regions.py/region_columns.py whenever the sheet's
point values change or new drops are added.
"""

DROP_POINTS = {
    ('Asgarnia', 'Cerberus', 'Jar of souls'): 40,
    ('Asgarnia', 'Cerberus', 'Pet'): 150,
    ('Asgarnia', 'Cerberus', 'Prim/Peg/Eternal Crystal'): 32,
    ('Asgarnia', 'Cerberus', 'Smouldering stone'): 32,
    ('Asgarnia', 'Commander Zilyana', 'Armadyl crossbow'): 45,
    ('Asgarnia', 'Commander Zilyana', 'Pet'): 150,
    ('Asgarnia', 'Commander Zilyana', 'Saradomin hilt'): 50,
    ('Asgarnia', 'Commander Zilyana', 'Saradomin sword'): 23,
    ('Asgarnia', 'Commander Zilyana', "Saradomin's light"): 35,
    ('Asgarnia', 'General Graardor', 'Bandos armour'): 50,
    ('Asgarnia', 'General Graardor', 'Bandos hilt'): 70,
    ('Asgarnia', 'General Graardor', 'Pet'): 150,
    ('Asgarnia', 'Giant mole', 'Long bone'): 41,
    ('Asgarnia', 'Giant mole', 'Pet'): 150,
    ('Asgarnia', "K'ril Tsutsaroth", 'Pet'): 150,
    ('Asgarnia', "K'ril Tsutsaroth", 'Staff of the dead'): 23,
    ('Asgarnia', "K'ril Tsutsaroth", 'Steam battlestaff'): 23,
    ('Asgarnia', "K'ril Tsutsaroth", 'Zamorak hilt'): 40,
    ('Asgarnia', "K'ril Tsutsaroth", 'Zamorakian spear'): 23,
    ('Asgarnia', "Kree'arra", 'Armadyl armour'): 65,
    ('Asgarnia', "Kree'arra", 'Armadyl hilt'): 75,
    ('Asgarnia', "Kree'arra", 'Pet'): 150,
    ('Asgarnia', 'Mahogany Homes', '500 Carpenter Points'): 23,
    ('Asgarnia', 'Nex', 'Ancient Hilt'): 350,
    ('Asgarnia', 'Nex', 'Nihil horn'): 286,
    ('Asgarnia', 'Nex', 'Pet'): 150,
    ('Asgarnia', 'Nex', 'Torva armour piece'): 286,
    ('Asgarnia', 'Nex', 'Zaryte vambraces'): 286,
    ('Asgarnia', 'Royal Titans', 'Pet'): 150,
    ('Asgarnia', 'Royal Titans', 'Staff crown piece'): 30,
    ('Asgarnia', 'Whisperer', 'Bellator vestige'): 55,
    ('Asgarnia', 'Whisperer', 'Chromium ingot'): 55,
    ('Asgarnia', 'Whisperer', 'Gold ring'): 55,
    ('Asgarnia', 'Whisperer', 'Pet'): 150,
    ('Asgarnia', 'Whisperer', "Siren's staff"): 70,
    ('Asgarnia', 'Whisperer', 'Virtus piece'): 70,
    ('Desert', 'Golem Crafting', 'Jewelers chisel'): 60,
    ('Desert', 'Gotr', 'Abyssal dye'): 44,
    ('Desert', 'Gotr', 'Abyssal lantern'): 44,
    ('Desert', 'Gotr', 'Catalytic talisman'): 36,
    ('Desert', 'Gotr', 'Pet'): 150,
    ('Desert', 'Kalphite Queen', 'Dragon 2h sword'): 28,
    ('Desert', 'Kalphite Queen', 'Dragon chainbody'): 28,
    ('Desert', 'Kalphite Queen', 'Dragon pickaxe'): 28,
    ('Desert', 'Kalphite Queen', 'Jar of sand'): 65,
    ('Desert', 'Kalphite Queen', 'Pet'): 150,
    ('Desert', 'Leviathan', 'Chromium ingot'): 58,
    ('Desert', 'Leviathan', 'Gold ring'): 58,
    ('Desert', 'Leviathan', 'Leviathan lure'): 75,
    ('Desert', 'Leviathan', 'Pet'): 150,
    ('Desert', 'Leviathan', 'Venator vestige'): 58,
    ('Desert', 'Leviathan', 'Virtus piece'): 75,
    ('Desert', 'Mining', '1m mining xp'): 152,
    ('Desert', 'Mining', 'Pet'): 150,
    ('Desert', 'Pyramid Plunder', 'Pet'): 150,
    ('Desert', 'Pyramid Plunder', "Pharaoh's sceptre"): 47,
    ('Desert', 'Shellbane Gryphon', "Belle's folly"): 7,
    ('Desert', 'Shellbane Gryphon', 'Jar of feathers'): 40,
    ('Desert', 'Shellbane Gryphon', 'Pet'): 150,
    ('Desert', 'Tempoross', '25 Soaked pages'): 27,
    ('Desert', 'Tempoross', 'Big harpoonfish'): 35,
    ('Desert', 'Tempoross', 'Dragon harpoon'): 100,
    ('Desert', 'Tempoross', 'Fish barrel'): 27,
    ('Desert', 'Tempoross', 'Pet'): 150,
    ('Desert', 'Tempoross', 'Tackle box'): 27,
    ('Desert', 'Tempoross', 'Tome of water'): 35,
    ('Desert', 'The Mad Angel', 'Hallowfell'): 23,
    ('Desert', 'The Mad Angel', 'Jar of light'): 28,
    ('Desert', 'The Mad Angel', 'Pet'): 150,
    ('Desert', 'Tombs of Amascut', 'Elidinis ward'): 215,
    ('Desert', 'Tombs of Amascut', 'Lightbearer'): 200,
    ('Desert', 'Tombs of Amascut', 'Masori armour piece'): 215,
    ('Desert', 'Tombs of Amascut', "Osmumten's fang"): 200,
    ('Desert', 'Tombs of Amascut', 'Pet'): 150,
    ('Desert', 'Tombs of Amascut', "Tumeken's shadow"): 275,
    ('Fremennik', 'Basilisk Knight', 'Basilisk jaw'): 144,
    ('Fremennik', 'Dagannoth Kings', 'Archers ring'): 20,
    ('Fremennik', 'Dagannoth Kings', 'Berserker ring'): 20,
    ('Fremennik', 'Dagannoth Kings', 'Pet (Prime)'): 150,
    ('Fremennik', 'Dagannoth Kings', 'Pet (Rex)'): 150,
    ('Fremennik', 'Dagannoth Kings', 'Pet (Supreme)'): 150,
    ('Fremennik', 'Dagannoth Kings', 'Seers ring'): 20,
    ('Fremennik', 'Duke Sucellus', 'Chromium ingot'): 37,
    ('Fremennik', 'Duke Sucellus', 'Eye of the duke'): 60,
    ('Fremennik', 'Duke Sucellus', 'Gold ring'): 37,
    ('Fremennik', 'Duke Sucellus', 'Magus vestige'): 37,
    ('Fremennik', 'Duke Sucellus', 'Pet'): 150,
    ('Fremennik', 'Duke Sucellus', 'Virtus piece'): 60,
    ('Fremennik', 'Frost Dragon', '20 Dragon nails'): 60,
    ('Fremennik', 'Kurask', 'Leaf bladed battleaxe'): 50,
    ('Fremennik', 'Penguin Agility', '100 penguin agility laps'): 20,
    ('Fremennik', 'Penguin Agility', 'Pet'): 150,
    ('Fremennik', 'Phantom Muspah', 'Pet'): 150,
    ('Fremennik', 'Phantom Muspah', 'Venator shard'): 74,
    ('Fremennik', 'Smithing', '1m smithing xp'): 40,
    ('Fremennik', 'Vorkath', 'Draconic visage'): 225,
    ('Fremennik', 'Vorkath', 'Dragonbone necklace'): 178,
    ('Fremennik', 'Vorkath', 'Jar of decay'): 195,
    ('Fremennik', 'Vorkath', 'Magic seed'): 178,
    ('Fremennik', 'Vorkath', 'Pet'): 150,
    ('Fremennik', 'Vorkath', 'Skeletal visage'): 225,
    ('Kandarin', 'Barbarian Assault', 'Granite helm'): 75,
    ('Kandarin', 'Barbarian Assault', 'Granite shield'): 75,
    ('Kandarin', 'Barbarian Assault', 'Pet'): 150,
    ('Kandarin', 'Chompies', '500 Chompy kills'): 14,
    ('Kandarin', 'Demonic Gorillas', 'Ballista limbs'): 17,
    ('Kandarin', 'Demonic Gorillas', 'Ballista spring'): 17,
    ('Kandarin', 'Demonic Gorillas', 'Heavy frame'): 40,
    ('Kandarin', 'Demonic Gorillas', 'Light frame'): 30,
    ('Kandarin', 'Demonic Gorillas', 'Monkey tail'): 60,
    ('Kandarin', 'Demonic Gorillas', 'Zenyte shard'): 17,
    ('Kandarin', 'Elite Clues', 'Elite clue headwear'): 15,
    ('Kandarin', 'Fishing', 'Big shark'): 52,
    ('Kandarin', 'Fishing', 'Pet'): 150,
    ('Kandarin', 'Fishing Trawler', 'Angler outfit pieces'): 11,
    ('Kandarin', 'Gnome Restaurant', 'Gnome scarf'): 9,
    ('Kandarin', 'Hard Clues', 'Magic comp bow'): 40,
    ('Kandarin', 'Kraken', 'Jar of dirt'): 30,
    ('Kandarin', 'Kraken', 'Kraken tentacle'): 32,
    ('Kandarin', 'Kraken', 'Pet'): 150,
    ('Kandarin', 'Kraken', 'Trident of the seas (full)'): 32,
    ('Kandarin', 'Medium Clues', 'Holy sandals'): 40,
    ('Kandarin', 'Medium Clues', 'Ranger boots'): 60,
    ('Kandarin', 'Medium Clues', 'Wizard boots'): 40,
    ('Kandarin', 'Mithril Dragon', 'Chewed bones'): 7,
    ('Kandarin', 'Thermonuclear Smoke Devil', 'Dragon chainbody'): 35,
    ('Kandarin', 'Thermonuclear Smoke Devil', 'Jar of smoke'): 35,
    ('Kandarin', 'Thermonuclear Smoke Devil', 'Occult necklace'): 26,
    ('Kandarin', 'Thermonuclear Smoke Devil', 'Pet'): 150,
    ('Kandarin', 'Thermonuclear Smoke Devil', 'Smoke battlestaff'): 26,
    ('Kandarin', 'Warped Creatures', 'Warped sceptre'): 16,
    ('Kourend', 'Aerial Fishing', 'Golden tench'): 125,
    ('Kourend', 'Alchemical Hydra', 'Brimstone ring pieces'): 32,
    ('Kourend', 'Alchemical Hydra', 'Hydra claw'): 65,
    ('Kourend', 'Alchemical Hydra', 'Hydra heads'): 38,
    ('Kourend', 'Alchemical Hydra', 'Hydra leather'): 55,
    ('Kourend', 'Alchemical Hydra', 'Hydra tail'): 55,
    ('Kourend', 'Alchemical Hydra', 'Jar of chemicals'): 65,
    ('Kourend', 'Alchemical Hydra', 'Pet'): 150,
    ('Kourend', 'Catacombs of Kourend', 'Ancient shard'): 3,
    ('Kourend', 'Chambers of Xeric', 'Ancestral pieces'): 200,
    ('Kourend', 'Chambers of Xeric', 'Arcane scroll'): 173,
    ('Kourend', 'Chambers of Xeric', 'Bulwark'): 200,
    ('Kourend', 'Chambers of Xeric', 'Dextrous scroll'): 173,
    ('Kourend', 'Chambers of Xeric', 'Dhcb'): 200,
    ('Kourend', 'Chambers of Xeric', 'Dragon claws'): 200,
    ('Kourend', 'Chambers of Xeric', 'Elder maul'): 250,
    ('Kourend', 'Chambers of Xeric', 'Kodai insignia'): 250,
    ('Kourend', 'Chambers of Xeric', 'Pet'): 150,
    ('Kourend', 'Chambers of Xeric', 'Twisted bow'): 250,
    ('Kourend', 'Chambers of Xeric', 'Twisted buckler'): 200,
    ('Kourend', 'Drake', "Drake's claw"): 26,
    ('Kourend', 'Drake', "Drake's tooth"): 26,
    ('Kourend', 'Fishing', 'Big swordfish'): 55,
    ('Kourend', 'Fishing', 'Pet'): 150,
    ('Kourend', 'Hespori', 'Bottomless compost bucket'): 9,
    ('Kourend', 'Lizardman Shaman', 'Dragon warhammer'): 200,
    ('Kourend', 'Sarachnis', 'Pet'): 150,
    ('Kourend', 'Sarachnis', 'Sarachnis cudgel'): 72,
    ('Kourend', 'Tithe Farm', '200 Tithe farm points'): 28,
    ('Kourend', 'Tithe Farm', 'Pet'): 150,
    ('Kourend', 'Wintertodt', 'Dragon axe'): 100,
    ('Kourend', 'Wintertodt', 'Pet'): 150,
    ('Kourend', 'Wintertodt', 'Pyromancer piece'): 25,
    ('Kourend', 'Wintertodt', 'Tome of fire'): 60,
    ('Kourend', 'Wyrm', 'Dragon harpoon'): 50,
    ('Kourend', 'Wyrm', 'Dragon sword'): 50,
    ('Kourend', 'Yama', 'Oathplate armour'): 315,
    ('Kourend', 'Yama', 'Pet'): 150,
    ('Kourend', 'Yama', 'Soulflame horn'): 315,
    ('Misthalin', 'Abyssal Sire', 'Pet'): 150,
    ('Misthalin', 'Abyssal Sire', 'Unsired'): 45,
    ('Misthalin', 'Adamant Dragon', 'Dragon metal slice'): 150,
    ('Misthalin', 'Armoured Zombies', 'Broken zombie axe'): 11,
    ('Misthalin', 'Beginner Clues', 'Mole slippers'): 43,
    ('Misthalin', 'Brutus', 'Beef'): 40,
    ('Misthalin', 'Bryophyta', "Bryophyta's essence"): 120,
    ('Misthalin', 'Easy Clues', 'Beret'): 35,
    ('Misthalin', 'Fossil Island Wyverns', 'Granite boots'): 45,
    ('Misthalin', 'Fossil Island Wyverns', 'Granite longsword'): 45,
    ('Misthalin', 'Fossil Island Wyverns', 'Wyvern visage'): 150,
    ('Misthalin', 'Obor', "Obor's club"): 118,
    ('Misthalin', 'Rune / Adamant Dragon', 'Draconic visage'): 200,
    ('Misthalin', 'Rune / Adamant Dragon', 'Dragon limbs'): 125,
    ('Misthalin', 'Rune Dragon', 'Dragon metal lump'): 140,
    ('Misthalin', 'Scurrius', 'Long bone'): 60,
    ('Misthalin', 'Scurrius', 'Pet'): 150,
    ('Misthalin', 'Tormented Demon', 'Burning claw'): 75,
    ('Misthalin', 'Tormented Demon', 'Tormented synapse'): 75,
    ('Misthalin', 'Tzhaars', 'Obsidian armour pieces'): 30,
    ('Misthalin', 'Underwater Agility', 'Merfolk trident'): 26,
    ('Misthalin', 'Woodcutting', '1m woodcutting xp'): 80,
    ('Misthalin', 'Woodcutting', 'Pet'): 150,
    ('Morytania', 'Abyssal Demon', 'Abyssal whip'): 10,
    ('Morytania', 'Araxxor', 'Araxyte head'): 40,
    ('Morytania', 'Araxxor', 'Jar of venom'): 60,
    ('Morytania', 'Araxxor', 'Noxious fang'): 45,
    ('Morytania', 'Araxxor', 'Noxious halberd piece'): 40,
    ('Morytania', 'Araxxor', 'Pet'): 150,
    ('Morytania', 'Araxyte', 'Aranea boots'): 15,
    ('Morytania', 'Barrows', 'Barrows helmet'): 30,
    ('Morytania', 'Grotesque Guardians', 'Black tourmaline core'): 35,
    ('Morytania', 'Grotesque Guardians', 'Granite gloves'): 25,
    ('Morytania', 'Grotesque Guardians', 'Granite hammer'): 25,
    ('Morytania', 'Grotesque Guardians', 'Granite maul'): 15,
    ('Morytania', 'Grotesque Guardians', 'Granite ring'): 25,
    ('Morytania', 'Grotesque Guardians', 'Jar of stone'): 50,
    ('Morytania', 'Grotesque Guardians', 'Pet'): 150,
    ('Morytania', 'Hallowed Sepulchre', 'Pet'): 150,
    ('Morytania', 'Hallowed Sepulchre', 'Ring of endurance'): 75,
    ('Morytania', 'Hallowed Sepulchre', 'Strange old lockpick'): 23,
    ('Morytania', 'Maggot King', 'Crimson kisten'): 115,
    ('Morytania', 'Maggot King', 'Elder venator fang'): 100,
    ('Morytania', 'Maggot King', 'Pet'): 150,
    ('Morytania', 'Nightmare', 'Inquisitor equipment'): 235,
    ('Morytania', 'Nightmare', 'Jar of dreams'): 290,
    ('Morytania', 'Nightmare', 'Nightmare orbs'): 290,
    ('Morytania', 'Nightmare', 'Nightmare staff'): 235,
    ('Morytania', 'Nightmare', 'Pet'): 150,
    ('Morytania', 'Theatre of Blood', 'Avernic defender hilt'): 228,
    ('Morytania', 'Theatre of Blood', 'Ghrazi rapier'): 240,
    ('Morytania', 'Theatre of Blood', 'Justiciar armour piece'): 240,
    ('Morytania', 'Theatre of Blood', 'Pet'): 150,
    ('Morytania', 'Theatre of Blood', 'Sanguinesti staff'): 240,
    ('Morytania', 'Theatre of Blood', 'Scythe of vitur'): 300,
    ('Morytania', 'Venator', 'Blood shard (Venator)'): 65,
    ('Morytania', 'Vyres', 'Blood shard (Vyre)'): 55,
    ('Tirannwn', 'Aquanite', 'Aquanite tendon'): 60,
    ('Tirannwn', 'Dark Beast', 'Dark bow'): 28,
    ('Tirannwn', 'Elves', 'Enhanced teleport seed'): 13,
    ('Tirannwn', 'Elves', 'Pet (Thieving)'): 150,
    ('Tirannwn', 'Gauntlet', 'Crystal armour seed'): 65,
    ('Tirannwn', 'Gauntlet', 'Crystal weapon seed'): 65,
    ('Tirannwn', 'Gauntlet', 'Enhanced weapon seed'): 125,
    ('Tirannwn', 'Gauntlet', 'Pet'): 150,
    ('Tirannwn', 'Prif agility course', '100 Prif agility laps'): 20,
    ('Tirannwn', 'Prif agility course', 'Pet (Agility)'): 150,
    ('Tirannwn', 'Sailing', '1m sailing xp'): 85,
    ('Tirannwn', 'Sailing', 'Pet'): 150,
    ('Tirannwn', 'Zalcano', 'Crystal tool seed'): 145,
    ('Tirannwn', 'Zalcano', 'Pet'): 150,
    ('Tirannwn', 'Zalcano', 'Zalcano shard'): 145,
    ('Tirannwn', 'Zulrah', 'Jar of swamp'): 70,
    ('Tirannwn', 'Zulrah', 'Magic fang'): 60,
    ('Tirannwn', 'Zulrah', 'Mutagens'): 125,
    ('Tirannwn', 'Zulrah', 'Pet'): 150,
    ('Tirannwn', 'Zulrah', 'Serpentine visage'): 60,
    ('Tirannwn', 'Zulrah', 'Tanzanite fang'): 60,
    ('Tirannwn', 'Zulrah', 'Uncut onyx'): 60,
    ('Varlamore', 'Amoxliatl', 'Glacial temotli'): 14,
    ('Varlamore', 'Amoxliatl', 'Pet'): 150,
    ('Varlamore', 'Custodian Stalkers', 'Antler guard'): 15,
    ('Varlamore', 'Doom', 'Avernic treads'): 150,
    ('Varlamore', 'Doom', 'Eye of ayak'): 128,
    ('Varlamore', 'Doom', 'Mokhaiotl cloth'): 128,
    ('Varlamore', 'Doom', 'Pet'): 150,
    ('Varlamore', 'Earthen Nagua', 'Earthbound tecpatl'): 15,
    ('Varlamore', 'Fortis Colosseum', 'Echo crystal'): 50,
    ('Varlamore', 'Fortis Colosseum', 'Pet'): 150,
    ('Varlamore', 'Fortis Colosseum', 'Sunfire fanatic armour'): 60,
    ('Varlamore', 'Fortis Colosseum', 'Tonzalnics of ralos'): 130,
    ('Varlamore', 'Hueycoatl', 'Dragonhunter wand'): 40,
    ('Varlamore', 'Hueycoatl', 'Hueycoatl hide'): 10,
    ('Varlamore', 'Hueycoatl', 'Pet'): 150,
    ('Varlamore', 'Hueycoatl', 'Tome of earth'): 40,
    ('Varlamore', 'Hunter Rumours', 'Guild hunter piece'): 35,
    ('Varlamore', 'Hunter Rumours', 'Pet (Chinchompa)'): 150,
    ('Varlamore', 'Hunter Rumours', 'Pet (Herbiboar)'): 150,
    ('Varlamore', 'Hunter Rumours', 'Pet (Quetzin)'): 150,
    ('Varlamore', 'Mixology', '25k resin'): 32,
    ('Varlamore', 'Perilous moons', 'Moons uniques'): 14,
    ('Varlamore', 'Sulfur Nagua', 'Sulfur blades'): 15,
    ('Varlamore', 'Vale Totems', 'Greenman mask'): 52,
    ('Varlamore', 'Vardorvis', 'Chromium ingot'): 62,
    ('Varlamore', 'Vardorvis', 'Executioner axe head'): 75,
    ('Varlamore', 'Vardorvis', 'Gold ring'): 62,
    ('Varlamore', 'Vardorvis', 'Pet'): 150,
    ('Varlamore', 'Vardorvis', 'Ultor vestige'): 62,
    ('Varlamore', 'Vardorvis', 'Virtus piece'): 75,
    ('Wilderness', 'Callisto/Artio', 'Callisto claws'): 72,
    ('Wilderness', 'Callisto/Artio', 'Pet'): 150,
    ('Wilderness', 'Callisto/Artio', 'Tyrannical ring'): 72,
    ('Wilderness', 'Callisto/Artio', 'Voidwaker hilt'): 72,
    ('Wilderness', 'Chaos Elemental', 'Dragon pickaxe (ele)'): 69,
    ('Wilderness', 'Chaos Elemental', 'Pet (Ele or fanatic)'): 150,
    ('Wilderness', 'Chaos Fanatic', 'Odium/Malediction shard 1'): 18,
    ('Wilderness', 'Corporeal Beast', 'Holy elixir'): 40,
    ('Wilderness', 'Corporeal Beast', 'Jar of spirits'): 75,
    ('Wilderness', 'Corporeal Beast', 'Pet'): 150,
    ('Wilderness', 'Corporeal Beast', 'Spirit shield'): 40,
    ('Wilderness', 'Corporeal Beast', 'Spirit sigils'): 150,
    ('Wilderness', 'Crazy Archaeologist', 'Odium/Malediction shard 2'): 16,
    ('Wilderness', 'Elder Chaos Druids', 'Elder chaos druid robes'): 12,
    ('Wilderness', 'King Black Dragon', 'Dragon pickaxe (kbd)'): 25,
    ('Wilderness', 'King Black Dragon', 'Kbd heads'): 18,
    ('Wilderness', 'King Black Dragon', 'Pet'): 150,
    ('Wilderness', 'Last Man Standing', '100 Lms points'): 54,
    ('Wilderness', 'Revenants', 'Ancient statuettes'): 23,
    ('Wilderness', 'Revenants', 'Revenant weapons'): 50,
    ('Wilderness', 'Scorpia', 'Odium/Malediction shard 3'): 18,
    ('Wilderness', 'Scorpia', 'Pet'): 150,
    ('Wilderness', 'Venenatis/Spindel', 'Pet'): 150,
    ('Wilderness', 'Venenatis/Spindel', 'Treasonous ring'): 72,
    ('Wilderness', 'Venenatis/Spindel', 'Venenatis fangs'): 72,
    ('Wilderness', 'Venenatis/Spindel', 'Voidwaker gem'): 72,
    ('Wilderness', "Vet'ion/Calvarion", 'Pet'): 150,
    ('Wilderness', "Vet'ion/Calvarion", 'Ring of the gods'): 40,
    ('Wilderness', "Vet'ion/Calvarion", "Vet'ion skull"): 40,
    ('Wilderness', "Vet'ion/Calvarion", 'Voidwaker blade'): 40,
}
