"""
Maps each Region -> Source -> list of possible Drops. Generated from the
bingo sheet's master "Points per item" reference (Cba_Conquers_Gielinor.xlsx),
with Pet entries (150 pts, per the sheet's blanket pet rule) preserved from
the original tracker sheet plus prior corrections. Some sources have
multiple specifically-named pet variants (e.g. Dagannoth Kings has
Pet (Prime)/(Rex)/(Supreme)) rather than one generic "Pet" -- edit directly
(or regenerate from an updated sheet) if the sheet's sources/drops change.

/submit's region, boss_name, and drop_name are all autocompleted AND
validated against this structure, in that order: boss_name only shows
sources that exist in the picked region, drop_name only shows drops that
exist for the picked region+source.
"""

REGION_SOURCES = {
    'Asgarnia': {
        'Cerberus': ['Jar of souls', 'Pet', 'Prim/Peg/Eternal Crystal', 'Smouldering stone'],
        'Commander Zilyana': ['Armadyl crossbow', 'Pet', 'Saradomin hilt', 'Saradomin sword', "Saradomin's light"],
        'General Graardor': ['Bandos armour', 'Bandos hilt', 'Pet'],
        'Giant mole': ['Long bone', 'Pet'],
        "K'ril Tsutsaroth": ['Pet', 'Staff of the dead', 'Steam battlestaff', 'Zamorak hilt', 'Zamorakian spear'],
        "Kree'arra": ['Armadyl armour', 'Armadyl hilt', 'Pet'],
        'Mahogany Homes': ['500 Carpenter Points'],
        'Nex': ['Ancient Hilt', 'Nihil horn', 'Pet', 'Torva armour piece', 'Zaryte vambraces'],
        'Royal Titans': ['Pet', 'Staff crown piece'],
        'Whisperer': ['Bellator vestige', 'Chromium ingot', 'Gold ring', 'Pet', "Siren's staff", 'Virtus piece'],
    },
    'Desert': {
        'Golem Crafting': ['Jewelers chisel'],
        'Gotr': ['Abyssal dye', 'Abyssal lantern', 'Catalytic talisman', 'Pet'],
        'Kalphite Queen': ['Dragon 2h sword', 'Dragon chainbody', 'Dragon pickaxe', 'Jar of sand', 'Pet'],
        'Leviathan': ['Chromium ingot', 'Gold ring', 'Leviathan lure', 'Pet', 'Venator vestige', 'Virtus piece'],
        'Mining': ['1m mining xp', 'Pet'],
        'Pyramid Plunder': ['Pet', "Pharaoh's sceptre"],
        'Shellbane Gryphon': ["Belle's folly", 'Jar of feathers', 'Pet'],
        'Tempoross': ['25 Soaked pages', 'Big harpoonfish', 'Dragon harpoon', 'Fish barrel', 'Pet', 'Tackle box', 'Tome of water'],
        'The Mad Angel': ['Hallowfell', 'Jar of light', 'Pet'],
        'Tombs of Amascut': ['Elidinis ward', 'Lightbearer', 'Masori armour piece', "Osmumten's fang", 'Pet', "Tumeken's shadow"],
    },
    'Fremennik': {
        'Basilisk Knight': ['Basilisk jaw'],
        'Dagannoth Kings': ['Archers ring', 'Berserker ring', 'Pet (Prime)', 'Pet (Rex)', 'Pet (Supreme)', 'Seers ring'],
        'Duke Sucellus': ['Chromium ingot', 'Eye of the duke', 'Gold ring', 'Magus vestige', 'Pet', 'Virtus piece'],
        'Frost Dragon': ['20 Dragon nails'],
        'Kurask': ['Leaf bladed battleaxe'],
        'Penguin Agility': ['100 penguin agility laps', 'Pet'],
        'Phantom Muspah': ['Pet', 'Venator shard'],
        'Smithing': ['1m smithing xp'],
        'Vorkath': ['Draconic visage', 'Dragonbone necklace', 'Jar of decay', 'Magic seed', 'Pet', 'Skeletal visage'],
    },
    'Kandarin': {
        'Barbarian Assault': ['Granite helm', 'Granite shield', 'Pet'],
        'Chompies': ['500 Chompy kills'],
        'Demonic Gorillas': ['Ballista limbs', 'Ballista spring', 'Heavy frame', 'Light frame', 'Monkey tail', 'Zenyte shard'],
        'Elite Clues': ['Elite clue headwear'],
        'Fishing': ['Big shark', 'Pet'],
        'Fishing Trawler': ['Angler outfit pieces'],
        'Gnome Restaurant': ['Gnome scarf'],
        'Hard Clues': ['Magic comp bow'],
        'Kraken': ['Jar of dirt', 'Kraken tentacle', 'Pet', 'Trident of the seas (full)'],
        'Medium Clues': ['Holy sandals', 'Ranger boots', 'Wizard boots'],
        'Mithril Dragon': ['Chewed bones'],
        'Thermonuclear Smoke Devil': ['Dragon chainbody', 'Jar of smoke', 'Occult necklace', 'Pet', 'Smoke battlestaff'],
        'Warped Creatures': ['Warped sceptre'],
    },
    'Kourend': {
        'Aerial Fishing': ['Golden tench'],
        'Alchemical Hydra': ['Brimstone ring pieces', 'Hydra claw', 'Hydra heads', 'Hydra leather', 'Hydra tail', 'Jar of chemicals', 'Pet'],
        'Catacombs of Kourend': ['Ancient shard'],
        'Chambers of Xeric': ['Ancestral pieces', 'Arcane scroll', 'Bulwark', 'Dextrous scroll', 'Dhcb', 'Dragon claws', 'Elder maul', 'Kodai insignia', 'Pet', 'Twisted bow', 'Twisted buckler'],
        'Drake': ["Drake's claw", "Drake's tooth"],
        'Fishing': ['Big swordfish', 'Pet'],
        'Hespori': ['Bottomless compost bucket'],
        'Lizardman Shaman': ['Dragon warhammer'],
        'Sarachnis': ['Pet', 'Sarachnis cudgel'],
        'Tithe Farm': ['200 Tithe farm points', 'Pet'],
        'Wintertodt': ['Dragon axe', 'Pet', 'Pyromancer piece', 'Tome of fire'],
        'Wyrm': ['Dragon harpoon', 'Dragon sword'],
        'Yama': ['Oathplate armour', 'Pet', 'Soulflame horn'],
    },
    'Misthalin': {
        'Abyssal Sire': ['Pet', 'Unsired'],
        'Adamant Dragon': ['Dragon metal slice'],
        'Armoured Zombies': ['Broken zombie axe'],
        'Beginner Clues': ['Mole slippers'],
        'Brutus': ['Beef'],
        'Bryophyta': ["Bryophyta's essence"],
        'Easy Clues': ['Beret'],
        'Fossil Island Wyverns': ['Granite boots', 'Granite longsword', 'Wyvern visage'],
        'Obor': ["Obor's club"],
        'Rune / Adamant Dragon': ['Draconic visage', 'Dragon limbs'],
        'Rune Dragon': ['Dragon metal lump'],
        'Scurrius': ['Long bone', 'Pet'],
        'Tormented Demon': ['Burning claw', 'Tormented synapse'],
        'Tzhaars': ['Obsidian armour pieces'],
        'Underwater Agility': ['Merfolk trident'],
        'Woodcutting': ['1m woodcutting xp', 'Pet'],
    },
    'Morytania': {
        'Abyssal Demon': ['Abyssal whip'],
        'Araxxor': ['Araxyte head', 'Jar of venom', 'Noxious fang', 'Noxious halberd piece', 'Pet'],
        'Araxyte': ['Aranea boots'],
        'Barrows': ['Barrows helmet'],
        'Grotesque Guardians': ['Black tourmaline core', 'Granite gloves', 'Granite hammer', 'Granite maul', 'Granite ring', 'Jar of stone', 'Pet'],
        'Hallowed Sepulchre': ['Pet', 'Ring of endurance', 'Strange old lockpick'],
        'Maggot King': ['Crimson kisten', 'Elder venator fang', 'Pet'],
        'Nightmare': ['Inquisitor equipment', 'Jar of dreams', 'Nightmare orbs', 'Nightmare staff', 'Pet'],
        'Theatre of Blood': ['Avernic defender hilt', 'Ghrazi rapier', 'Justiciar armour piece', 'Pet', 'Sanguinesti staff', 'Scythe of vitur'],
        'Venator': ['Blood shard (Venator)'],
        'Vyres': ['Blood shard (Vyre)'],
    },
    'Tirannwn': {
        'Aquanite': ['Aquanite tendon'],
        'Dark Beast': ['Dark bow'],
        'Elves': ['Enhanced teleport seed', 'Pet (Thieving)'],
        'Gauntlet': ['Crystal armour seed', 'Crystal weapon seed', 'Enhanced weapon seed', 'Pet'],
        'Prif agility course': ['100 Prif agility laps', 'Pet (Agility)'],
        'Sailing': ['1m sailing xp', 'Pet'],
        'Zalcano': ['Crystal tool seed', 'Pet', 'Zalcano shard'],
        'Zulrah': ['Jar of swamp', 'Magic fang', 'Mutagens', 'Pet', 'Serpentine visage', 'Tanzanite fang', 'Uncut onyx'],
    },
    'Varlamore': {
        'Amoxliatl': ['Glacial temotli', 'Pet'],
        'Custodian Stalkers': ['Antler guard'],
        'Doom': ['Avernic treads', 'Eye of ayak', 'Mokhaiotl cloth', 'Pet'],
        'Earthen Nagua': ['Earthbound tecpatl'],
        'Fortis Colosseum': ['Echo crystal', 'Pet', 'Sunfire fanatic armour', 'Tonzalnics of ralos'],
        'Hueycoatl': ['Dragonhunter wand', 'Hueycoatl hide', 'Pet', 'Tome of earth'],
        'Hunter Rumours': ['Guild hunter piece', 'Pet (Chinchompa)', 'Pet (Herbiboar)', 'Pet (Quetzin)'],
        'Mixology': ['25k resin'],
        'Perilous moons': ['Moons uniques'],
        'Sulfur Nagua': ['Sulfur blades'],
        'Vale Totems': ['Greenman mask'],
        'Vardorvis': ['Chromium ingot', 'Executioner axe head', 'Gold ring', 'Pet', 'Ultor vestige', 'Virtus piece'],
    },
    'Wilderness': {
        'Callisto/Artio': ['Callisto claws', 'Pet', 'Tyrannical ring', 'Voidwaker hilt'],
        'Chaos Elemental': ['Dragon pickaxe (ele)', 'Pet (Ele or fanatic)'],
        'Chaos Fanatic': ['Odium/Malediction shard 1'],
        'Corporeal Beast': ['Holy elixir', 'Jar of spirits', 'Pet', 'Spirit shield', 'Spirit sigils'],
        'Crazy Archaeologist': ['Odium/Malediction shard 2'],
        'Elder Chaos Druids': ['Elder chaos druid robes'],
        'King Black Dragon': ['Dragon pickaxe (kbd)', 'Kbd heads', 'Pet'],
        'Last Man Standing': ['100 Lms points'],
        'Revenants': ['Ancient statuettes', 'Revenant weapons'],
        'Scorpia': ['Odium/Malediction shard 3', 'Pet'],
        'Venenatis/Spindel': ['Pet', 'Treasonous ring', 'Venenatis fangs', 'Voidwaker gem'],
        "Vet'ion/Calvarion": ['Pet', 'Ring of the gods', "Vet'ion skull", 'Voidwaker blade'],
    },
}
