"""
Maps each drop Source (boss, skill, minigame, or clue tier) to the list
of drops that can come from it. Generated from the bingo sheet -- edit
this file directly whenever the sheet changes (add/remove a source or drop).

boss_name in /submit autocompletes AND is validated against these keys.
drop_name autocompletes AND is validated against the matching source's
list, so a submission can only reference a drop that actually belongs to
that source.
"""

SOURCE_DROPS = {
    'Abyssal Demon': ['Abyssal whip'],
    'Abyssal Sire': ['Pet', 'Unsired'],
    'Aerial Fishing': ['Golden tench'],
    'Alchemical Hydra': ['Brimstone ring pieces', 'Hydra claw', 'Hydra heads', 'Hydra leather', 'Hydra tail', 'Jar of chemicals', 'Pet'],
    'Amoxliatl': ['Glacial temotli', 'Pet'],
    'Aquanite': ['Aquanite tendon'],
    'Araxxor': ['Araxyte head', 'Jar of venom', 'Noxious fang', 'Noxious halberd piece', 'Pet'],
    'Araxyte': ['Aranea boots'],
    'Armoured Zombies': ['Broken zombie axe'],
    'Barbarian Assault': ['Granite helm', 'Granite shield', 'Pet'],
    'Barrows': ['Barrows helmet'],
    'Basilisk Knight': ['Basilisk jaw'],
    'Beginner Clues': ['Mole slippers'],
    'Brine rat': ['Brine sabre'],
    'Brutus': ['Beef'],
    'Bryophyta': ["Bryophyta's essence"],
    'Callisto/Artio': ['Callisto claws', 'Pet', 'Tyrannical ring', 'Voidwaker hilt'],
    'Catacombs of Kourend': ['Ancient shard'],
    'Cave Horror': ['Black mask'],
    'Cerberus': ['Jar of souls', 'Pet', 'Prim/Peg/Eternal Crystal', 'Smouldering stone'],
    'Chambers of Xeric': ['Ancestral pieces', 'Arcane scroll', 'Bulwark', 'Dextrous scroll', 'Dhcb', 'Dragon claws', 'Elder maul', 'Kodai insignia', 'Pet', 'Twisted bow', 'Twisted buckler'],
    'Chaos Elemental': ['Dragon pickaxe (ele)', 'Pet (Ele or fanatic)'],
    'Chaos Fanatic': ['Odium/Malediction shard 1'],
    'Chompies': ['500 Chompy kills'],
    'Commander Zilyana': ['Armadyl crossbow', 'Pet', 'Saradomin hilt', 'Saradomin sword', "Saradomin's light"],
    'Corporeal Beast': ['Holy elixir', 'Jar of spirits', 'Pet', 'Spirit shield', 'Spirit sigils'],
    'Crazy Archaeologist': ['Odium/Malediction shard 2'],
    'Custodian Stalkers': ['Antler guard'],
    'Dagannoth Kings': ['Archers ring', 'Berserker ring', 'Pet (Prime)', 'Pet (Rex)', 'Pet (Supreme)', 'Seers ring'],
    'Dark Beast': ['Dark bow'],
    'Demonic Gorillas': ['Ballista limbs', 'Ballista spring', 'Heavy frame', 'Light frame', 'Monkey tail', 'Zenyte shard'],
    'Doom': ['Avernic treads', 'Eye of ayak', 'Mokhaiotl cloth', 'Pet'],
    'Drake': ["Drake's claw", "Drake's tooth"],
    'Duke Sucellus': ['Chromium ingot', 'Eye of the duke', 'Gold ring', 'Magus vestige', 'Pet', 'Virtus piece'],
    'Earthen Nagua': ['Earthbound tecpatl'],
    'Easy Clues': ['Beret'],
    'Elder Chaos Druids': ['Elder chaos druid robes'],
    'Elite Clues': ['Master clue scroll'],
    'Elves': ['Enhanced teleport seed', 'Pet (Thieving)'],
    'Fallen Angel': ['Hallowfell', 'Pet'],
    'Fishing': ['Big shark', 'Big swordfish', 'Pet'],
    'Fishing Trawler': ['Angler outfit pieces'],
    'Fortis Colosseum': ['Echo crystal', 'Pet', 'Sunfire fanatic armour', 'Tonzalnics of ralos'],
    'Fossil Island Wyverns': ['Granite boots', 'Granite longsword', 'Wyvern visage'],
    'Frost Dragon': ['20 Dragon nails'],
    'Gauntlet': ['Crystal armour seed', 'Crystal weapon seed', 'Enhanced weapon seed', 'Pet'],
    'General Graardor': ['Bandos armour', 'Bandos hilt', 'Pet'],
    'Giant mole': ['Long bone', 'Pet'],
    'Gnome Restaurant': ['Gnome scarf'],
    'Gotr': ['Abyssal dye', 'Abyssal lantern', 'Catalytic talisman', 'Pet'],
    'Grotesque Guardians': ['Black tourmaline core', 'Granite gloves', 'Granite hammer', 'Granite maul', 'Granite ring', 'Jar of stone', 'Pet'],
    'Gryphon': ['Horn of plenty'],
    'Hallowed Sepulchre': ['Pet', 'Ring of endurance', 'Strange old lockpick'],
    'Hard Clues': ['Magic comp bow'],
    'Hespori': ['Bottomless compost bucket'],
    'Hueycoatl': ['Dragonhunter wand', 'Hueycoatl hide', 'Pet', 'Tome of earth'],
    'Hunter Rumours': ['Guild hunter piece', 'Pet (Chinchompa)', 'Pet (Herbiboar)', 'Pet (Quetzin)'],
    "K'ril Tsutsaroth": ['Pet', 'Staff of the dead', 'Steam battlestaff', 'Zamorak hilt', 'Zamorakian spear'],
    'Kalphite Queen': ['Dragon 2h sword', 'Dragon chainbody', 'Dragon pickaxe', 'Jar of sand', 'Pet'],
    'King Black Dragon': ['Dragon pickaxe (kbd)', 'Kbd heads', 'Pet'],
    'Kraken': ['Jar of dirt', 'Kraken tentacle', 'Pet', 'Trident of the seas (full)'],
    "Kree'arra": ['Armadyl armour', 'Armadyl hilt', 'Pet'],
    'Kurask': ['Leaf bladed battleaxe'],
    'Last Man Standing': ['100 Lms points'],
    'Leviathan': ['Chromium ingot', 'Gold ring', 'Leviathan lure', 'Pet', 'Venator vestige', 'Virtus piece'],
    'Lizardman Shaman': ['Dragon warhammer'],
    'Maggot King': ['Crimson kisten', 'Elder venator fang', 'Pet'],
    'Mahogany Homes': ['500 Points'],
    'Medium Clues': ['Holy sandals', 'Ranger boots', 'Wizard boots'],
    'Mining': ['1m mining xp', 'Pet'],
    'Mithril Dragon': ['Chewed bones'],
    'Mixology': ['25k resin'],
    'Nex': ['Ancient Hilt', 'Nihil horn', 'Pet', 'Torva armour piece', 'Zaryte vambraces'],
    'Nightmare': ['Inquisitor equipment', 'Jar of dreams', 'Nightmare orbs', 'Nightmare staff', 'Pet'],
    'Obor': ["Obor's club"],
    'Penguin Agility': ['100 penguin agility laps', 'Pet'],
    'Perilous moons': ['Moons uniques'],
    'Phantom Muspah': ['Pet', 'Venator shard'],
    'Prif agility course': ['100 Prif agility laps', 'Pet (Agility)'],
    'Pyramid Plunder': ['Pet', "Pharaoh's sceptre"],
    'Revenants': ['Ancient statuettes', 'Revenant weapons'],
    'Royal Titans': ['Pet', 'Staff crown piece'],
    'Rune / Adamant Dragon': ['Draconic visage', 'Dragon limbs', 'Dragon metal lump', 'Dragon metal slice'],
    'Sailing': ['1m sailing xp', 'Pet'],
    'Sarachnis': ['Pet', 'Sarachnis cudgel'],
    'Scorpia': ['Odium/Malediction shard 3', 'Pet'],
    'Scurrius': ['Long bone', 'Pet'],
    'Shellbane Gryphon': ["Belle's folly", 'Jar of feathers', 'Pet'],
    'Smithing': ['1m smithing xp'],
    'Sulfur Nagua': ['Sulfur blades'],
    'Tempoross': ['25 Soaked pages', 'Big harpoonfish', 'Dragon harpoon', 'Fish barrel', 'Pet', 'Tackle box', 'Tome of water'],
    'Theatre of Blood': ['Avernic defender hilt', 'Ghrazi rapier', 'Justiciar armour piece', 'Pet', 'Sanguinesti staff', 'Scythe of vitur'],
    'Thermonuclear Smoke Devil': ['Dragon chainbody', 'Jar of smoke', 'Occult necklace', 'Pet', 'Smoke battlestaff'],
    'Tithe Farm': ['200 Tithe farm points', 'Pet'],
    'Tombs of Amascut': ['Lightbearer', 'Masori armour piece', "Osmumten's fang", 'Pet', "Tumeken's shadow"],
    'Tormented Demon': ['Burning claw', 'Tormented synapse'],
    'Tzhaars': ['Obsidian armour pieces'],
    'Underwater Agility': ['Merfolk trident'],
    'Vale Totems': ['Greenman mask'],
    'Vardorvis': ['Chromium ingot', 'Executioner axe head', 'Gold ring', 'Pet', 'Ultor vestige', 'Virtus piece'],
    'Venator': ['Blood shard (Venator)'],
    'Venenatis/Spindel': ['Pet', 'Treasonous ring', 'Venenatis fangs', 'Voidwaker gem'],
    "Vet'ion/Calvarion": ['Pet', 'Ring of the gods', "Vet'ion skull", 'Voidwaker blade'],
    'Vorkath': ['Draconic visage', 'Dragonbone necklace', 'Jar of decay', 'Magic seed', 'Pet', 'Skeletal visage'],
    'Vyres': ['Blood shard'],
    'Warped Creatures': ['Warped sceptre'],
    'Whisperer': ['Bellator vestige', 'Chromium ingot', 'Gold ring', 'Pet', "Siren's staff", 'Virtus piece'],
    'Wintertodt': ['Dragon axe', 'Pet', 'Pyromancer piece', 'Tome of fire'],
    'Woodcutting': ['1m woodcutting xp', 'Pet'],
    'Wyrm': ['Dragon harpoon', 'Dragon sword'],
    'Yama': ['Oathplate armour', 'Pet', 'Soulflame horn'],
    'Zalcano': ['Crystal tool seed', 'Pet', 'Zalcano shard'],
    'Zulrah': ['Jar of swamp', 'Magic fang', 'Mutagens', 'Pet', 'Serpentine visage', 'Tanzanite fang', 'Uncut onyx'],
}
